### PR TITLE
remove 'Mutation' suffix from mutations files names

### PR DESCRIPTION
**Pull request by eladams**
For #40

### CODE REVIEW

**Comment by sibelius** [comment]
I think it is better to keep the `Mutation` suffix in filename

I think `RegisterEmail` -> `RegisterEmailMutation` is enough

**Comment by eladams** [comment]
I've somehow got you the other way around :)

**Comment by sibelius** [comment]
Sorry about the misunderstanding.

Tks for the Pr

**Comment by eladams** [comment]
Thanks for the awesome repo :)

**Pull request merged**
